" Autogenerated file from setup.sh

let g:python_host_prog = '/Users/samcb/.pyenv/versions/nvim_settings_py2/bin/python'
let g:python3_host_prog = '/Users/samcb/.pyenv/versions/nvim_settings_py3/bin/python'
